#!/bin/bash

set -eou pipefail

# Start up ssh-agent
eval "$(ssh-agent -s)"

# Load keyfiles off of disk
IDX=0
while [[ -v "BUILDKITE_PLUGIN_SSH_AGENT_KEYFILES_${IDX}" ]]; do
    VARNAME="BUILDKITE_PLUGIN_SSH_AGENT_KEYFILES_${IDX}"
    cat "${!VARNAME}" | ssh-add -

    IDX=$((${IDX} + 1))
done

# Decode environment variables, and pipe them in through `stdin`
IDX=0
while [[ -v "BUILDKITE_PLUGIN_SSH_AGENT_KEYVARS_${IDX}" ]]; do
    # First, build buildkite plugin variable name
    VARNAME="BUILDKITE_PLUGIN_SSH_AGENT_KEYVARS_${IDX}"
    # Use that to get the actual keyfile variable name
    VARNAME="${!VARNAME}"
    # Then we dereference _again_ to get the actual keyfile contents
    base64 -d <<< "${!VARNAME}" | ssh-add -

    IDX=$((${IDX} + 1))
done

# List all loaded SSH keys
ssh-add -l
